name: Puppet Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and Puppet Lint (user scope)
        run: |
          sudo apt update
          sudo apt install ruby -y
          gem install --user-install puppet-lint
          echo "$(ruby -e 'puts Gem.user_dir')/bin" >> $GITHUB_PATH

      - name: Run puppet-lint
        run: |
         puppet-lint production/manifests/


